#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /Applications/Postgres.app/Contents/Versions/9.3/bin
  /usr/local/{bin,sbin}
  $path
)

export RBENV_ROOT=/usr/local/var/rbenv
eval "$(rbenv init -)"


#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# Base16 Shell
BASE16_SCHEME="ocean"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
export PIP_VIRTUALENV_BASE=$WORKON_HOME

# Useful for Karma, as Chrome is installed via Cask
export CHROME_BIN=CHROME_BIN=~/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

#boot2docker
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/xav/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
export CURL_CA_BUNDLE=/usr/local/etc/openssl/certs/cacert.pem

#fig, figfiles
alias fig="REQUESTS_CA_BUNDLE=~/.boot2docker/certs/boot2docker-vm/ca.pem fig"
alias figfiles="REQUESTS_CA_BUNDLE=~/.boot2docker/certs/boot2docker-vm/ca.pem figfiles"

#erlang
MANPATH=/usr/local/opt/erlang/lib/erlang/man:$MANPATH

#old-school cat
alias bcat=/bin/cat

#weechat
alias weechat="TERM=screen-256color weechat"

#Novapost
alias npmeb="boot2docker up && workon fig && DOCKER_HOST=https://boot2docker:2376 figfiles up --reuseyml novapostme"
alias npmef="docker run --rm -v ~/code/novapost/front/novapostMe:/home/nova/src/novapostmejs -v ~/.figtmp/nginx/conf.d:/etc/nginx/conf.d --link novapost_insight_1:insight.local --link novapost_novapostme_1:novapostme.local -p 80:80 nginx"
