#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Customize to your needs...
#
# Customization by Xavier Cambar <xcambar@gmail.com> (For my own needs)
#

# NVM
source ~/.env/vms/nvm/nvm.sh

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
source /Users/xav/.rvm/environments/default



#Python executables
path=(
  $path
  /usr/local/share/python
)

alias n=node
alias r=ruby
alias w=google-chrome
alias v=vim

# Can not remember what this one is useful at. jsctags seems perfectly fine without it...
# export NODE_PATH=/usr/local/lib/jsctags/:$NODE_PATH

#
# Defines the helper to go directly to a subdirectory of $codePath
#
local codePath="$HOME/code/"
function c () {
  cd $codePath$1
}
compdef '_files -W "$codePath/" -/' c

#
# Defines the helper to go directly to a subdirectory of $codePath
#
local HullCodePath="$codePath/Hull.io/"
function ch () {
  cd $HullCodePath$1
}
compdef '_files -W "$HullCodePath/" -/' ch

#
# Auto completes the executables located in node_modules/.bin 
#
function npm-exec () {
  PATH=$(npm bin):$PATH $@
}
function _comp_npm () {
  _arguments '1: :->command_'
  case $state in
    command_)
      _files -W "$(npm bin)" -/
      ;;
    *)
      _files
      ;;
  esac
}
compdef _comp_npm npm-exec


# Powerline
#source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
